spring:
  profiles:
    active:
      -  EN
      -  dev
guru:
  username: ymlUser
  password: ymlPass
  jdbcUrl: ymlURL

---
spring:
  profiles: prod
guru:
  username: PRODymlUser
  password: PRODymlPass
  jdbcUrl: PRODymlURL